version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    groups:
      dev-dependencies:
        patterns:
          - "flutter_test"
          - "flutter_lints"
          - "flutter_launcher_icons"
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "flutter_test"
          - "flutter_lints"
          - "flutter_launcher_icons"
